repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format (C/C++)
        entry: clang-format -i --style=file
        language: system
        types_or: [c, c++]
        files: ^(src|include)/.*\.(c|cc|cpp|cxx|h|hh|hpp|hxx)$
